name: ci

on:
  push:
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set commit SHA
        id: vars
        run: echo "::set-output name=sha_short::$(echo ${GITHUB_SHA::7})"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags:  ${{ secrets.DOCKERHUB_USERNAME }}/demo-cicd-github:${{ steps.vars.outputs.sha_short }}, ${{ secrets.DOCKERHUB_USERNAME }}/demo-cicd-github:latest
