name: my-hello-world-composite-action
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - id: my-composite-action
        uses: huy8895/hello-world-composite-action@v1.0.5
        with:
          who-to-greet: 'Trinh Van Huy'
      - name: show output random-number from my-composite-action
        run: echo random-number ${{ steps.my-composite-action.outputs.random-number }}
        shell: bash
      - name: show commit-sha_short from my-composite-action
        run: echo sha_short ${{ env.sha_short }}
        shell: bash
      - name: show repository-name from my-composite-action
        run: echo REPOSITORY_NAME ${{ env.REPOSITORY_NAME }}
        shell: bash
