name: my-hello-world-composite-action
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: huy8895/hello-world-composite-action@v1
        with:
          who-to-greet: 'Trinh Van Huy'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
